#!/bin/bash
if [[ -z "$VENV" ]]
then
    export CHEZSCHEMELIBDIRS="$PWD/"
    unset CHEZSCHEMELIBEXTS
    export BABELIA_GIT_ROOT="$PWD/"
    export BABELIA_PATH="$PWD/"
    export PATH="$PWD/local/bin/:$PATH"
    export VENV=1
    exec "${@:-$SHELL}"
else
    echo "You are already in a virtual environment!"
fi
